[tool.poetry]
name = "обучение в агу"
version = "0.1.0"
description = ""
authors = ["RomanZorkin <zorkin.roman@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<=3.10"
ipython = "^8.9.0"
jupyter = "^1.0.0"
numpy = "^1.24.1"
pandas = "^1.5.3"
sklearn = "^0.0.post1"
openpyxl = "^3.1.0"
matplotlib = "^3.6.3"
sparklines = "^0.4.2"
scikit-learn = "^1.2.1"
scipy = "^1.10.0"
seaborn = "^0.12.2"
geopy = "^2.3.0"
pyephem = "^9.99"
joblib = "^1.2.0"


[tool.poetry.group.dev.dependencies]
wemake-python-styleguide = "^0.17.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
